@hostAddress = http://localhost:5062

# Companies Controller - Organization Structure

### Register Company
POST {{hostAddress}}/api/organization-structure/companies
Content-Type: application/json

{
  "cnpj": "12.345.678/0001-90",
  "razaoSocial": "Empresa Exemplo Ltda"
}

###

### Update Company Name
PUT {{hostAddress}}/api/organization-structure/companies/{{companyId}}/name
Content-Type: application/json

{
  "newName": "Nova Razão Social Ltda"
}

###

### Enable Company
PUT {{hostAddress}}/api/organization-structure/companies/{{companyId}}/enable
Accept: application/json
###

### Disable Company
PUT {{hostAddress}}/api/organization-structure/companies/{{companyId}}/disable
Accept: application/json
###

### Get Company By Id
GET {{hostAddress}}/api/organization-structure/companies/by-id/{{companyId}}
Accept: application/json

###

### Get Company By CNPJ
# CNPJ deve ser informado SEM máscara (apenas dígitos)
GET {{hostAddress}}/api/organization-structure/companies/by-cnpj/12345678000190
Accept: application/json

###
